# pyright: reportUnsupportedDunderAll=false
"""causalrl: causal intervention-selection and causal-RL research tools.

The stable public API is loaded lazily so graph algorithms and tabular components can be used
without installing the optional PyTorch-backed SCM and neural functionality.
"""

from importlib import import_module as _import_module
from importlib.metadata import version as _pkg_version
from typing import cast as _cast

__version__ = _pkg_version("causalrl")

# Register demo environments in the Gymnasium registry at import time.
# This is cheap (just dict inserts) and idempotent.
from causalrl.envs.registration import register_envs as _register_envs

_register_envs()

_EXPORTS: dict[str, tuple[str, str]] = {
    "CausalInterfaceUnavailableError": (
        "causalrl.exceptions",
        "CausalInterfaceUnavailableError",
    ),
    "register_envs": ("causalrl.envs.registration", "register_envs"),
    "ExogenousPosterior": ("causalrl.scm.scm", "ExogenousPosterior"),
    "build_unrolled_scm": ("causalrl.scm.unrolled", "build_unrolled_scm"),
    "DOVI": ("causalrl.agents.dovi", "DOVI"),
    "FactoredAdvantageConfig": (
        "causalrl.agents.factored_advantage",
        "FactoredAdvantageConfig",
    ),
    "factored_advantage": ("causalrl.agents.factored_advantage", "factored_advantage"),
    "UCDTR": ("causalrl.agents.offline_online", "UCDTR"),
    "Agent": ("causalrl.agents.base", "Agent"),
    "BruteForceInterventionTS": ("causalrl.agents.scbandit", "BruteForceInterventionTS"),
    "BackdoorAdjustedAgent": ("causalrl.agents.mbrl", "BackdoorAdjustedAgent"),
    "DiscoveryBackdoorAgent": ("causalrl.agents.mbrl", "DiscoveryBackdoorAgent"),
    "BehavioralCloning": ("causalrl.imitation", "BehavioralCloning"),
    "BenchmarkEstimate": ("causalrl.eval.benchmark", "BenchmarkEstimate"),
    "CPDAG": ("causalrl.discovery", "CPDAG"),
    "PAG": ("causalrl.discovery", "PAG"),
    "CausalEnv": ("causalrl.envs.base", "CausalEnv"),
    "CausalEnvWrapper": ("causalrl.envs.wrapper", "CausalEnvWrapper"),
    "CausalGame": ("causalrl.games", "CausalGame"),
    "CausalGraph": ("causalrl.scm.graph", "CausalGraph"),
    "CausalGraphError": ("causalrl.exceptions", "CausalGraphError"),
    "CausalImitator": ("causalrl.imitation", "CausalImitator"),
    "CausalRLError": ("causalrl.exceptions", "CausalRLError"),
    "CausalThompsonSampling": ("causalrl.agents.bandits", "CausalThompsonSampling"),
    "CertifiedPolicyAgent": ("causalrl.agents.mbrl", "CertifiedPolicyAgent"),
    "ConfoundedContextualBandit": (
        "causalrl.envs.suite.confounded_context",
        "ConfoundedContextualBandit",
    ),
    "ConfoundedGridworld": ("causalrl.envs.suite.gridworld", "ConfoundedGridworld"),
    "ConfoundedMDP": ("causalrl.envs.base", "ConfoundedMDP"),
    "ConfoundedTrajectoryDataset": ("causalrl.data.dataset", "ConfoundedTrajectoryDataset"),
    "TrajectoryLog": ("causalrl.data.trajectory", "TrajectoryLog"),
    "Regime": ("causalrl.regime", "Regime"),
    "CausalEnvProtocol": ("causalrl.protocols", "CausalEnvProtocol"),
    "NoiseLedger": ("causalrl.protocols", "NoiseLedger"),
    "NoisePosterior": ("causalrl.protocols", "NoisePosterior"),
    "SCMCausalEnv": ("causalrl.protocols", "SCMCausalEnv"),
    "DictNoiseLedger": ("causalrl.protocols", "DictNoiseLedger"),
    "CounterfactualBanditEnv": (
        "causalrl.envs.suite.counterfactual_bandit",
        "CounterfactualBanditEnv",
    ),
    "CounterfactualOptimalPolicy": (
        "causalrl.agents.counterfactual",
        "CounterfactualOptimalPolicy",
    ),
    "DTREnv": ("causalrl.envs.suite.dtr", "DTREnv"),
    "DeepDeconfoundedQ": ("causalrl.agents.deep_deconfounded", "DeepDeconfoundedQ"),
    "Domain": ("causalrl.identification.id_algorithm", "Domain"),
    "Estimand": ("causalrl.identification.id_algorithm", "Estimand"),
    "FixedSetThompsonSampling": ("causalrl.agents.scbandit", "FixedSetThompsonSampling"),
    "FunctionalMechanism": ("causalrl.scm.mechanisms", "FunctionalMechanism"),
    "Interval": ("causalrl.identification.bounds", "Interval"),
    "msm_per_step_bounds": ("causalrl.identification.bounds", "msm_per_step_bounds"),
    "msm_stratified_bounds": ("causalrl.identification.bounds", "msm_stratified_bounds"),
    "LinearGaussianMechanism": ("causalrl.scm.mechanisms", "LinearGaussianMechanism"),
    "MABUCEnv": ("causalrl.envs.suite.mabuc", "MABUCEnv"),
    "Mechanism": ("causalrl.scm.mechanisms", "Mechanism"),
    "NaiveOffline": ("causalrl.agents.baselines", "NaiveOffline"),
    "NaivePOMISThompsonSampling": ("causalrl.agents.scbandit", "NaivePOMISThompsonSampling"),
    "NaiveThompsonSampling": ("causalrl.agents.bandits", "NaiveThompsonSampling"),
    "NeuralMechanism": ("causalrl.scm.mechanisms", "NeuralMechanism"),
    "NotIdentifiableError": ("causalrl.exceptions", "NotIdentifiableError"),
    "OnlineOnlyUCB": ("causalrl.agents.baselines", "OnlineOnlyUCB"),
    "POMISThompsonSampling": ("causalrl.agents.scbandit", "POMISThompsonSampling"),
    "PrerequisiteLearner": ("causalrl.curriculum", "PrerequisiteLearner"),
    "RealizabilityError": ("causalrl.exceptions", "RealizabilityError"),
    "UnverifiedAssumptionError": ("causalrl.exceptions", "UnverifiedAssumptionError"),
    "SelectionDiagram": ("causalrl.identification.transport", "SelectionDiagram"),
    "SequentialDTREnv": ("causalrl.envs.suite.seq_dtr", "SequentialDTREnv"),
    "SequentialMABUCEnv": ("causalrl.envs.suite.seq_mabuc", "SequentialMABUCEnv"),
    "SimpsonBandit": ("causalrl.envs.suite.simpson_bandit", "SimpsonBandit"),
    "StructuralCausalBanditEnv": ("causalrl.envs.suite.scbandit", "StructuralCausalBanditEnv"),
    "StructuralCausalModel": ("causalrl.scm.scm", "StructuralCausalModel"),
    "TabularMDP": ("causalrl.shaping", "TabularMDP"),
    "Transition": ("causalrl.data.dataset", "Transition"),
    "TransportFormula": ("causalrl.identification.transport", "TransportFormula"),
    "TransportRegretCertificate": (
        "causalrl.identification.transport_regret",
        "TransportRegretCertificate",
    ),
    "transport_regret_certificate": (
        "causalrl.identification.transport_regret",
        "transport_regret_certificate",
    ),
    "decision_flip_rate": ("causalrl.identification.transport_regret", "decision_flip_rate"),
    "decision_abstain_mask": (
        "causalrl.identification.transport_regret",
        "decision_abstain_mask",
    ),
    "apply_potential_shaping": ("causalrl.shaping", "apply_potential_shaping"),
    "backdoor_adjustment_set": ("causalrl.identification.criteria", "backdoor_adjustment_set"),
    "best_response": ("causalrl.games", "best_response"),
    "causal_curriculum": ("causalrl.curriculum", "causal_curriculum"),
    "causal_potential": ("causalrl.shaping", "causal_potential"),
    "causal_q_bounds": ("causalrl.identification.bounds", "causal_q_bounds"),
    "ipw_sensitivity_bounds": ("causalrl.identification.bounds", "ipw_sensitivity_bounds"),
    "msm_policy_value_bounds": ("causalrl.identification.bounds", "msm_policy_value_bounds"),
    "msm_contribution_bounds": ("causalrl.identification.bounds", "msm_contribution_bounds"),
    "tipping_gamma": ("causalrl.identification.bounds", "tipping_gamma"),
    "confounding_bias_bound": ("causalrl.identification.bounds", "confounding_bias_bound"),
    "confounding_bias_per_step_bounds": (
        "causalrl.identification.bounds",
        "confounding_bias_per_step_bounds",
    ),
    "mi_flip_threshold": ("causalrl.identification.bounds", "mi_flip_threshold"),
    "pivotality_certificate": ("causalrl.identification.bounds", "pivotality_certificate"),
    "PivotalityCertificate": ("causalrl.identification.bounds", "PivotalityCertificate"),
    "certify_decision": ("causalrl.identification.decision", "certify_decision"),
    "certify_estimate": ("causalrl.identification.decision", "certify_estimate"),
    "certify_policy": ("causalrl.scale", "certify_policy"),
    "certify_fqe": ("causalrl.scale.d3rlpy", "certify_fqe"),
    "policy_actions": ("causalrl.scale.d3rlpy", "policy_actions"),
    "regimes_from_posterior": ("causalrl.interop.sbi_numpyro", "regimes_from_posterior"),
    "across_regimes": ("causalrl.interop.sbi_numpyro", "across_regimes"),
    "PosteriorRegimeSampler": ("causalrl.interop.sbi_numpyro", "PosteriorRegimeSampler"),
    "ColumnarSimulator": ("causalrl.interop.columnar_sim", "ColumnarSimulator"),
    "simulator_from_callables": ("causalrl.interop.columnar_sim", "simulator_from_callables"),
    "check_conformance": ("causalrl.interop.columnar_sim", "check_conformance"),
    "certify_effect": ("causalrl.estimate.compiler", "certify_effect"),
    "estimate_ate": ("causalrl.estimate.estimators", "estimate_ate"),
    "EffectEstimate": ("causalrl.estimate.estimators", "EffectEstimate"),
    "estimate_sequential_value": ("causalrl.estimate.sequential", "estimate_sequential_value"),
    "certify_sequential_value": ("causalrl.estimate.sequential", "certify_sequential_value"),
    "SequentialValueEstimate": ("causalrl.estimate.sequential", "SequentialValueEstimate"),
    "stream_policy_value": ("causalrl.estimate.streaming", "stream_policy_value"),
    "stream_quantile_certificate": ("causalrl.estimate.streaming", "stream_quantile_certificate"),
    "stream_msm_bounds": ("causalrl.bounds.streaming", "stream_msm_bounds"),
    "msm_sensitivity_bounds": ("causalrl.bounds.continuous", "msm_sensitivity_bounds"),
    "certify_sensitivity_bounds": ("causalrl.bounds.continuous", "certify_sensitivity_bounds"),
    "certify_quantile": ("causalrl.bounds.continuous", "certify_quantile"),
    "certify_mean": ("causalrl.bounds.continuous", "certify_mean"),
    "moment_diagnostic": ("causalrl.bounds.continuous", "moment_diagnostic"),
    "conformal_quantile": ("causalrl.conformal.core", "conformal_quantile"),
    "split_conformal_interval": ("causalrl.conformal.core", "split_conformal_interval"),
    "cqr_interval": ("causalrl.conformal.core", "cqr_interval"),
    "certify_conformal_interval": ("causalrl.conformal.core", "certify_conformal_interval"),
    "certify_transported_effect": ("causalrl.transport.estimate", "certify_transported_effect"),
    "certify_sequential_transport": (
        "causalrl.transport.estimate",
        "certify_sequential_transport",
    ),
    "sequential_ice_values": ("causalrl.estimate.sequential", "sequential_ice_values"),
    "AgentType": ("causalrl.magames", "AgentType"),
    "Population": ("causalrl.magames", "Population"),
    "LearnerTopology": ("causalrl.magames", "LearnerTopology"),
    "certify_equilibrium": ("causalrl.magames", "certify_equilibrium"),
    "KindNotLicensedError": ("causalrl.magames", "KindNotLicensedError"),
    "topology_max_kind": ("causalrl.magames", "topology_max_kind"),
    "PopulationAgentView": ("causalrl.magames", "PopulationAgentView"),
    "agent_causal_env_view": ("causalrl.magames", "agent_causal_env_view"),
    "CCEPolytope": ("causalrl.magames", "CCEPolytope"),
    "cce_polytope": ("causalrl.magames", "cce_polytope"),
    "cce_bounds": ("causalrl.magames", "cce_bounds"),
    "cce_regret": ("causalrl.magames", "cce_regret"),
    "certify_cce_do": ("causalrl.magames", "certify_cce_do"),
    "pettingzoo_to_trajectory_log": ("causalrl.interop.pettingzoo", "pettingzoo_to_trajectory_log"),
    "MLPMechanism": ("causalrl.scm.continuous.mechanisms", "MLPMechanism"),
    "LocationScaleMechanism": ("causalrl.scm.continuous.mechanisms", "LocationScaleMechanism"),
    "ConditionalFlowMechanism": (
        "causalrl.scm.continuous.mechanisms",
        "ConditionalFlowMechanism",
    ),
    "AmortizedGaussianAbduction": (
        "causalrl.scm.continuous.abduction",
        "AmortizedGaussianAbduction",
    ),
    "abduct_location_scale": ("causalrl.scm.continuous.abduction", "abduct_location_scale"),
    "abduct_invertible": ("causalrl.scm.continuous.abduction", "abduct_invertible"),
    "certify_counterfactual": ("causalrl.scm.continuous.abduction", "certify_counterfactual"),
    "abduct_nuts": ("causalrl.scm.continuous.nuts", "abduct_nuts"),
    "NUTSNoisePosterior": ("causalrl.scm.continuous.nuts", "NUTSNoisePosterior"),
    "certify_nuts_counterfactual": (
        "causalrl.scm.continuous.nuts",
        "certify_nuts_counterfactual",
    ),
    "DecisionCertificate": ("causalrl.identification.decision", "DecisionCertificate"),
    "PolicyValueContrast": ("causalrl.identification.estimate", "PolicyValueContrast"),
    "Certificate": ("causalrl.certify", "Certificate"),
    "Kind": ("causalrl.certify", "Kind"),
    "Assumption": ("causalrl.certify", "Assumption"),
    "EstimandSpec": ("causalrl.certify", "EstimandSpec"),
    "Witness": ("causalrl.certify", "Witness"),
    "Hedge": ("causalrl.certify", "Hedge"),
    "Provenance": ("causalrl.certify", "Provenance"),
    "as_certificate": ("causalrl.certify", "as_certificate"),
    "identify_effect_certified": ("causalrl.certify", "identify_effect_certified"),
    "ipw_sensitivity_bounds_certified": ("causalrl.certify", "ipw_sensitivity_bounds_certified"),
    "msm_policy_value_bounds_certified": ("causalrl.certify", "msm_policy_value_bounds_certified"),
    "manski_bounds": ("causalrl.identification.bounds", "manski_bounds"),
    "conditional_mutual_information": ("causalrl.discovery", "conditional_mutual_information"),
    "counterfactual_expectation": (
        "causalrl.identification.counterfactual",
        "counterfactual_expectation",
    ),
    "cumulative_regret": ("causalrl.eval.metrics", "cumulative_regret"),
    "curriculum_q_learning": ("causalrl.curriculum", "curriculum_q_learning"),
    "discover": ("causalrl.discovery", "discover"),
    "discover_interventional": ("causalrl.discovery", "discover_interventional"),
    "discover_latent": ("causalrl.discovery", "discover_latent"),
    "effect_of_treatment_on_treated": (
        "causalrl.identification.counterfactual",
        "effect_of_treatment_on_treated",
    ),
    "estimate_effect": ("causalrl.identification.id_algorithm", "estimate_effect"),
    "estimate_effect_with_experiments": (
        "causalrl.identification.id_algorithm",
        "estimate_effect_with_experiments",
    ),
    "estimate_transport_general": (
        "causalrl.identification.id_algorithm",
        "estimate_transport_general",
    ),
    "estimate_transported_effect": (
        "causalrl.identification.id_algorithm",
        "estimate_transported_effect",
    ),
    "finite_horizon_regret": ("causalrl.eval.metrics", "finite_horizon_regret"),
    "generate_logs": ("causalrl.data.dataset", "generate_logs"),
    "identify_effect": ("causalrl.identification.id_algorithm", "identify_effect"),
    "identify_effect_with_experiments": (
        "causalrl.identification.id_algorithm",
        "identify_effect_with_experiments",
    ),
    "identify_transport": ("causalrl.identification.id_algorithm", "identify_transport"),
    "identify_transport_general": (
        "causalrl.identification.id_algorithm",
        "identify_transport_general",
    ),
    "imitation_backdoor_set": ("causalrl.imitation", "imitation_backdoor_set"),
    "ipw_value": ("causalrl.eval.ope", "ipw_value"),
    "is_backdoor_admissible": ("causalrl.identification.transport", "is_backdoor_admissible"),
    "is_gid_identifiable": ("causalrl.identification.id_algorithm", "is_gid_identifiable"),
    "is_identifiable": ("causalrl.identification.criteria", "is_identifiable"),
    "is_identifiable_effect": ("causalrl.identification.id_algorithm", "is_identifiable_effect"),
    "is_imitable": ("causalrl.imitation", "is_imitable"),
    "is_nash_equilibrium": ("causalrl.games", "is_nash_equilibrium"),
    "is_transportable": ("causalrl.identification.transport", "is_transportable"),
    "is_transportable_effect": (
        "causalrl.identification.id_algorithm",
        "is_transportable_effect",
    ),
    "is_transportable_general": (
        "causalrl.identification.id_algorithm",
        "is_transportable_general",
    ),
    "is_valid_curriculum": ("causalrl.curriculum", "is_valid_curriculum"),
    "minimal_intervention_sets": (
        "causalrl.identification.intervention_sets",
        "minimal_intervention_sets",
    ),
    "mixed_nash_equilibria": ("causalrl.games", "mixed_nash_equilibria"),
    "pomis": ("causalrl.identification.intervention_sets", "pomis"),
    "pure_nash_equilibria": ("causalrl.games", "pure_nash_equilibria"),
    "q_learning": ("causalrl.shaping", "q_learning"),
    "report_to_dict": ("causalrl.eval.benchmark", "report_to_dict"),
    "requires_experiment": ("causalrl.identification.intervention_sets", "requires_experiment"),
    "run_episodes": ("causalrl.eval.harness", "run_episodes"),
    "run_confounded_chain_benchmark": ("causalrl.eval.benchmark", "run_confounded_chain_benchmark"),
    "run_frontdoor_benchmark": ("causalrl.eval.benchmark", "run_frontdoor_benchmark"),
    "run_m0_kill_gate": ("causalrl.eval.mbrl_probe", "run_m0_kill_gate"),
    "run_m1_discovery_gate": ("causalrl.eval.mbrl_probe", "run_m1_discovery_gate"),
    "transport_estimand": ("causalrl.identification.transport", "transport_estimand"),
    "transport_formula": ("causalrl.identification.transport", "transport_formula"),
    "transported_effect": ("causalrl.identification.transport", "transported_effect"),
    "value_iteration": ("causalrl.shaping", "value_iteration"),
}

__all__ = [
    "CPDAG",
    "DOVI",
    "PAG",
    "UCDTR",
    "Agent",
    "AgentType",
    "AmortizedGaussianAbduction",
    "Assumption",
    "BackdoorAdjustedAgent",
    "BehavioralCloning",
    "BenchmarkEstimate",
    "BruteForceInterventionTS",
    "CCEPolytope",
    "CausalEnv",
    "CausalEnvProtocol",
    "CausalEnvWrapper",
    "CausalGame",
    "CausalGraph",
    "CausalGraphError",
    "CausalImitator",
    "CausalInterfaceUnavailableError",
    "CausalRLError",
    "CausalThompsonSampling",
    "Certificate",
    "CertifiedPolicyAgent",
    "ColumnarSimulator",
    "ConditionalFlowMechanism",
    "ConfoundedContextualBandit",
    "ConfoundedGridworld",
    "ConfoundedMDP",
    "ConfoundedTrajectoryDataset",
    "CounterfactualBanditEnv",
    "CounterfactualOptimalPolicy",
    "DTREnv",
    "DecisionCertificate",
    "DeepDeconfoundedQ",
    "DictNoiseLedger",
    "DiscoveryBackdoorAgent",
    "Domain",
    "EffectEstimate",
    "Estimand",
    "EstimandSpec",
    "ExogenousPosterior",
    "FactoredAdvantageConfig",
    "FixedSetThompsonSampling",
    "FunctionalMechanism",
    "Hedge",
    "Interval",
    "Kind",
    "KindNotLicensedError",
    "LearnerTopology",
    "LinearGaussianMechanism",
    "LocationScaleMechanism",
    "MABUCEnv",
    "MLPMechanism",
    "Mechanism",
    "NUTSNoisePosterior",
    "NaiveOffline",
    "NaivePOMISThompsonSampling",
    "NaiveThompsonSampling",
    "NeuralMechanism",
    "NoiseLedger",
    "NoisePosterior",
    "NotIdentifiableError",
    "OnlineOnlyUCB",
    "POMISThompsonSampling",
    "PivotalityCertificate",
    "PolicyValueContrast",
    "Population",
    "PopulationAgentView",
    "PosteriorRegimeSampler",
    "PrerequisiteLearner",
    "Provenance",
    "RealizabilityError",
    "Regime",
    "SCMCausalEnv",
    "SelectionDiagram",
    "SequentialDTREnv",
    "SequentialMABUCEnv",
    "SequentialValueEstimate",
    "SimpsonBandit",
    "StructuralCausalBanditEnv",
    "StructuralCausalModel",
    "TabularMDP",
    "TrajectoryLog",
    "Transition",
    "TransportFormula",
    "TransportRegretCertificate",
    "UnverifiedAssumptionError",
    "Witness",
    "__version__",
    "abduct_invertible",
    "abduct_location_scale",
    "abduct_nuts",
    "across_regimes",
    "agent_causal_env_view",
    "apply_potential_shaping",
    "as_certificate",
    "backdoor_adjustment_set",
    "best_response",
    "build_unrolled_scm",
    "causal_curriculum",
    "causal_potential",
    "causal_q_bounds",
    "cce_bounds",
    "cce_polytope",
    "cce_regret",
    "certify_cce_do",
    "certify_conformal_interval",
    "certify_counterfactual",
    "certify_decision",
    "certify_effect",
    "certify_equilibrium",
    "certify_estimate",
    "certify_fqe",
    "certify_mean",
    "certify_nuts_counterfactual",
    "certify_policy",
    "certify_quantile",
    "certify_sensitivity_bounds",
    "certify_sequential_transport",
    "certify_sequential_value",
    "certify_transported_effect",
    "check_conformance",
    "conditional_mutual_information",
    "conformal_quantile",
    "confounding_bias_bound",
    "confounding_bias_per_step_bounds",
    "counterfactual_expectation",
    "cqr_interval",
    "cumulative_regret",
    "curriculum_q_learning",
    "decision_abstain_mask",
    "decision_flip_rate",
    "discover",
    "discover_interventional",
    "discover_latent",
    "effect_of_treatment_on_treated",
    "estimate_ate",
    "estimate_effect",
    "estimate_effect_with_experiments",
    "estimate_sequential_value",
    "estimate_transport_general",
    "estimate_transported_effect",
    "factored_advantage",
    "finite_horizon_regret",
    "generate_logs",
    "identify_effect",
    "identify_effect_certified",
    "identify_effect_with_experiments",
    "identify_transport",
    "identify_transport_general",
    "imitation_backdoor_set",
    "ipw_sensitivity_bounds",
    "ipw_sensitivity_bounds_certified",
    "ipw_value",
    "is_backdoor_admissible",
    "is_gid_identifiable",
    "is_identifiable",
    "is_identifiable_effect",
    "is_imitable",
    "is_nash_equilibrium",
    "is_transportable",
    "is_transportable_effect",
    "is_transportable_general",
    "is_valid_curriculum",
    "manski_bounds",
    "mi_flip_threshold",
    "minimal_intervention_sets",
    "mixed_nash_equilibria",
    "moment_diagnostic",
    "msm_contribution_bounds",
    "msm_per_step_bounds",
    "msm_policy_value_bounds",
    "msm_policy_value_bounds_certified",
    "msm_sensitivity_bounds",
    "msm_stratified_bounds",
    "pettingzoo_to_trajectory_log",
    "pivotality_certificate",
    "policy_actions",
    "pomis",
    "pure_nash_equilibria",
    "q_learning",
    "regimes_from_posterior",
    "register_envs",
    "report_to_dict",
    "requires_experiment",
    "run_confounded_chain_benchmark",
    "run_episodes",
    "run_frontdoor_benchmark",
    "run_m0_kill_gate",
    "run_m1_discovery_gate",
    "sequential_ice_values",
    "simulator_from_callables",
    "split_conformal_interval",
    "stream_msm_bounds",
    "stream_policy_value",
    "stream_quantile_certificate",
    "tipping_gamma",
    "topology_max_kind",
    "transport_estimand",
    "transport_formula",
    "transport_regret_certificate",
    "transported_effect",
    "value_iteration",
]


def __getattr__(name: str) -> object:
    target = _EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute = target
    try:
        value = _cast(object, getattr(_import_module(module_name), attribute))
    except ModuleNotFoundError as exc:
        if exc.name == "torch":
            raise ImportError(
                f"{name} requires PyTorch support; install the 'causalrl[torch]' extra"
            ) from exc
        raise
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
