# pyright: reportUnsupportedDunderAll=false
"""causalrl: causal reinforcement learning -- the 9-task causal RL taxonomy, made runnable.

The stable public API is loaded lazily so graph algorithms and tabular components can be used
without installing the optional PyTorch-backed SCM and neural functionality.
"""

from importlib import import_module as _import_module
from importlib.metadata import version as _pkg_version
from typing import cast as _cast

__version__ = _pkg_version("causalrl")

# Register demo environments in the Gymnasium registry at import time.
# This is cheap (just dict inserts) and idempotent.
from causalrl.envs.registration import register_envs as _register_envs

_register_envs()

_EXPORTS: dict[str, tuple[str, str]] = {
    "FidelityReport": ("causalrl.scm.fidelity", "FidelityReport"),
    "certify_fitted_query": ("causalrl.scm.fidelity", "certify_fitted_query"),
    "SequentialVerdict": ("causalrl.ope.sequential_test", "SequentialVerdict"),
    "sequential_policy_comparison": (
        "causalrl.ope.sequential_test",
        "sequential_policy_comparison",
    ),
    "ConfidenceSequence": ("causalrl.ope.sequential_test", "ConfidenceSequence"),
    "confidence_sequence": ("causalrl.ope.sequential_test", "confidence_sequence"),
    "InterventionDomain": ("causalrl.intervention", "InterventionDomain"),
    "Discrete": ("causalrl.intervention", "Discrete"),
    "Continuous": ("causalrl.intervention", "Continuous"),
    "SearchReport": ("causalrl.agents.anytime", "SearchReport"),
    "AnytimeInterventionSearch": ("causalrl.agents.anytime", "AnytimeInterventionSearch"),
    "Anytime": ("causalrl.agents.anytime", "Anytime"),
    "MechanismShift": ("causalrl.transport.localize", "MechanismShift"),
    "ShiftReport": ("causalrl.transport.localize", "ShiftReport"),
    "localize_mechanism_shift": ("causalrl.transport.localize", "localize_mechanism_shift"),
    "BoundedNodeFit": ("causalrl.scm.bounded_fit", "BoundedNodeFit"),
    "BoundedSCMFit": ("causalrl.scm.bounded_fit", "BoundedSCMFit"),
    "fit_scm_bounded": ("causalrl.scm.bounded_fit", "fit_scm_bounded"),
    "CausalInterfaceUnavailableError": (
        "causalrl.exceptions",
        "CausalInterfaceUnavailableError",
    ),
    "register_envs": ("causalrl.envs.registration", "register_envs"),
    "ExogenousPosterior": ("causalrl.scm.scm", "ExogenousPosterior"),
    "build_unrolled_scm": ("causalrl.scm.unrolled", "build_unrolled_scm"),
    "DOVI": ("causalrl.agents.dovi", "DOVI"),
    "FactoredAdvantageConfig": (
        "causalrl.agents.factored_advantage",
        "FactoredAdvantageConfig",
    ),
    "factored_advantage": ("causalrl.agents.factored_advantage", "factored_advantage"),
    "factor_rewards": ("causalrl.agents.factored_advantage", "factor_rewards"),
    "factor_gae": ("causalrl.agents.factored_advantage", "factor_gae"),
    "blend_advantages": ("causalrl.agents.factored_advantage", "blend_advantages"),
    "FactoredCritic": ("causalrl.agents.cgfa_critic", "FactoredCritic"),
    "CGFACriticConfig": ("causalrl.agents.cgfa_critic", "CGFACriticConfig"),
    "CGFAAdvantages": ("causalrl.agents.cgfa_critic", "CGFAAdvantages"),
    "CGFALosses": ("causalrl.agents.cgfa_critic", "CGFALosses"),
    "CGFAUpdateStats": ("causalrl.agents.cgfa_critic", "CGFAUpdateStats"),
    "UCDTR": ("causalrl.agents.offline_online", "UCDTR"),
    "Agent": ("causalrl.agents.base", "Agent"),
    "FunctionalManskiBounds": ("causalrl.bounds.functional", "FunctionalManskiBounds"),
    "OverlapDiagnostic": ("causalrl.bounds.functional", "OverlapDiagnostic"),
    "BoundedFittedQIteration": ("causalrl.agents.bounded_fitted", "BoundedFittedQIteration"),
    "StateEncoder": ("causalrl.state", "StateEncoder"),
    "OneHotEncoder": ("causalrl.state", "OneHotEncoder"),
    "IdentityEncoder": ("causalrl.state", "IdentityEncoder"),
    "RBFEncoder": ("causalrl.state", "RBFEncoder"),
    "FeatureTransition": ("causalrl.state", "FeatureTransition"),
    "encode_batch": ("causalrl.state", "encode_batch"),
    "FittedQIteration": ("causalrl.agents.fitted", "FittedQIteration"),
    "InterventionalAgent": ("causalrl.agents.interventional", "InterventionalAgent"),
    "ScalarAgentAdapter": ("causalrl.agents.interventional", "ScalarAgentAdapter"),
    "Intervention": ("causalrl.intervention", "Intervention"),
    "InterventionSpace": ("causalrl.intervention", "InterventionSpace"),
    "canonical_intervention": ("causalrl.intervention", "canonical"),
    "Deadline": ("causalrl.deadline", "Deadline"),
    "AdmissibleInterventions": (
        "causalrl.identification.intervention_sets",
        "AdmissibleInterventions",
    ),
    "PinnedMechanism": ("causalrl.scm.fitters", "PinnedMechanism"),
    "BruteForceInterventionTS": ("causalrl.agents.scbandit", "BruteForceInterventionTS"),
    "BackdoorAdjustedAgent": ("causalrl.agents.mbrl", "BackdoorAdjustedAgent"),
    "DiscoveryBackdoorAgent": ("causalrl.agents.mbrl", "DiscoveryBackdoorAgent"),
    "TransportBackdoorAgent": ("causalrl.agents.mbrl", "TransportBackdoorAgent"),
    "FunctionApproxBackdoorAgent": ("causalrl.agents.mbrl", "FunctionApproxBackdoorAgent"),
    "GFormulaBackdoorAgent": ("causalrl.agents.mbrl", "GFormulaBackdoorAgent"),
    "OnlineCausalMBRL": ("causalrl.agents.online_causal_mbrl", "OnlineCausalMBRL"),
    "BehavioralCloning": ("causalrl.imitation", "BehavioralCloning"),
    "BenchmarkEstimate": ("causalrl.eval.benchmark", "BenchmarkEstimate"),
    "CPDAG": ("causalrl.discovery", "CPDAG"),
    "PAG": ("causalrl.discovery", "PAG"),
    "CausalEnv": ("causalrl.envs.base", "CausalEnv"),
    "CausalEnvWrapper": ("causalrl.envs.wrapper", "CausalEnvWrapper"),
    "CausalGame": ("causalrl.games", "CausalGame"),
    "CausalGraph": ("causalrl.scm.graph", "CausalGraph"),
    "CausalGraphError": ("causalrl.exceptions", "CausalGraphError"),
    "CausalImitator": ("causalrl.imitation", "CausalImitator"),
    "CausalRLError": ("causalrl.exceptions", "CausalRLError"),
    "CausalThompsonSampling": ("causalrl.agents.bandits", "CausalThompsonSampling"),
    "CausalMBRLAgent": ("causalrl.agents.causal_mbrl", "CausalMBRLAgent"),
    "CertifiedPolicyAgent": ("causalrl.agents.mbrl", "CertifiedPolicyAgent"),
    "ConfoundedContextualBandit": (
        "causalrl.envs.suite.confounded_context",
        "ConfoundedContextualBandit",
    ),
    "ContinuousConfoundedBandit": (
        "causalrl.envs.suite.continuous_confounded",
        "ContinuousConfoundedBandit",
    ),
    "ConfoundedGridworld": ("causalrl.envs.suite.gridworld", "ConfoundedGridworld"),
    "ConfoundedMDP": ("causalrl.envs.base", "ConfoundedMDP"),
    "ConfoundedTrajectoryDataset": ("causalrl.data.dataset", "ConfoundedTrajectoryDataset"),
    "LoggedDecisions": ("causalrl.data.logged", "LoggedDecisions"),
    "LoggedDecision": ("causalrl.data.logged", "LoggedDecision"),
    "FeatureDecisionLog": ("causalrl.data.logged", "FeatureDecisionLog"),
    "PositivityReport": ("causalrl.data.logged", "PositivityReport"),
    "TrajectoryLog": ("causalrl.data.trajectory", "TrajectoryLog"),
    "Regime": ("causalrl.regime", "Regime"),
    "CausalEnvProtocol": ("causalrl.protocols", "CausalEnvProtocol"),
    "NoiseLedger": ("causalrl.protocols", "NoiseLedger"),
    "NoisePosterior": ("causalrl.protocols", "NoisePosterior"),
    "SCMCausalEnv": ("causalrl.protocols", "SCMCausalEnv"),
    "DictNoiseLedger": ("causalrl.protocols", "DictNoiseLedger"),
    "CounterfactualBanditEnv": (
        "causalrl.envs.suite.counterfactual_bandit",
        "CounterfactualBanditEnv",
    ),
    "CounterfactualOptimalPolicy": (
        "causalrl.agents.counterfactual",
        "CounterfactualOptimalPolicy",
    ),
    "DTREnv": ("causalrl.envs.suite.dtr", "DTREnv"),
    "DeepDeconfoundedQ": ("causalrl.agents.deep_deconfounded", "DeepDeconfoundedQ"),
    "Domain": ("causalrl.identification.id_algorithm", "Domain"),
    "Estimand": ("causalrl.identification.id_algorithm", "Estimand"),
    "FixedSetThompsonSampling": ("causalrl.agents.scbandit", "FixedSetThompsonSampling"),
    "FunctionalMechanism": ("causalrl.scm.mechanisms", "FunctionalMechanism"),
    "Interval": ("causalrl.identification.bounds", "Interval"),
    "msm_per_step_bounds": ("causalrl.ope.bounds", "msm_per_step_bounds"),
    "msm_stratified_bounds": ("causalrl.ope.bounds", "msm_stratified_bounds"),
    "LinearGaussianMechanism": ("causalrl.scm.mechanisms", "LinearGaussianMechanism"),
    "MABUCEnv": ("causalrl.envs.suite.mabuc", "MABUCEnv"),
    "Mechanism": ("causalrl.scm.mechanisms", "Mechanism"),
    "NaiveOffline": ("causalrl.agents.baselines", "NaiveOffline"),
    "NaivePOMISThompsonSampling": ("causalrl.agents.scbandit", "NaivePOMISThompsonSampling"),
    "NaiveThompsonSampling": ("causalrl.agents.bandits", "NaiveThompsonSampling"),
    "NeuralMechanism": ("causalrl.scm.mechanisms", "NeuralMechanism"),
    "NotIdentifiableError": ("causalrl.exceptions", "NotIdentifiableError"),
    "OnlineOnlyUCB": ("causalrl.agents.baselines", "OnlineOnlyUCB"),
    "POMISThompsonSampling": ("causalrl.agents.scbandit", "POMISThompsonSampling"),
    "PrerequisiteLearner": ("causalrl.curriculum", "PrerequisiteLearner"),
    "RealizabilityError": ("causalrl.exceptions", "RealizabilityError"),
    "UnverifiedAssumptionError": ("causalrl.exceptions", "UnverifiedAssumptionError"),
    "SelectionDiagram": ("causalrl.identification.transport", "SelectionDiagram"),
    "SequentialDTREnv": ("causalrl.envs.suite.seq_dtr", "SequentialDTREnv"),
    "SequentialMABUCEnv": ("causalrl.envs.suite.seq_mabuc", "SequentialMABUCEnv"),
    "SimpsonBandit": ("causalrl.envs.suite.simpson_bandit", "SimpsonBandit"),
    "TransportableConfoundedBandit": (
        "causalrl.envs.suite.transport_bandit",
        "TransportableConfoundedBandit",
    ),
    "StructuralCausalBanditEnv": ("causalrl.envs.suite.scbandit", "StructuralCausalBanditEnv"),
    "StructuralCausalModel": ("causalrl.scm.scm", "StructuralCausalModel"),
    "TabularMDP": ("causalrl.shaping", "TabularMDP"),
    "Transition": ("causalrl.data.dataset", "Transition"),
    "TransportFormula": ("causalrl.identification.transport", "TransportFormula"),
    "TransportRegretCertificate": (
        "causalrl.identification.transport_regret",
        "TransportRegretCertificate",
    ),
    "transport_regret_certificate": (
        "causalrl.identification.transport_regret",
        "transport_regret_certificate",
    ),
    "decision_flip_rate": ("causalrl.identification.transport_regret", "decision_flip_rate"),
    "decision_abstain_mask": (
        "causalrl.identification.transport_regret",
        "decision_abstain_mask",
    ),
    "apply_potential_shaping": ("causalrl.shaping", "apply_potential_shaping"),
    "backdoor_adjustment_set": ("causalrl.identification.criteria", "backdoor_adjustment_set"),
    "best_response": ("causalrl.games", "best_response"),
    "causal_curriculum": ("causalrl.curriculum", "causal_curriculum"),
    "causal_potential": ("causalrl.shaping", "causal_potential"),
    "causal_q_bounds": ("causalrl.ope.bounds", "causal_q_bounds"),
    "ipw_sensitivity_bounds": ("causalrl.ope.bounds", "ipw_sensitivity_bounds"),
    "msm_policy_value_bounds": ("causalrl.ope.bounds", "msm_policy_value_bounds"),
    "msm_contribution_bounds": ("causalrl.ope.bounds", "msm_contribution_bounds"),
    "tipping_gamma": ("causalrl.identification.bounds", "tipping_gamma"),
    "confounding_bias_bound": ("causalrl.identification.bounds", "confounding_bias_bound"),
    "confounding_bias_per_step_bounds": (
        "causalrl.identification.bounds",
        "confounding_bias_per_step_bounds",
    ),
    "mi_flip_threshold": ("causalrl.identification.bounds", "mi_flip_threshold"),
    "pivotality_certificate": ("causalrl.identification.bounds", "pivotality_certificate"),
    "PivotalityCertificate": ("causalrl.identification.bounds", "PivotalityCertificate"),
    "certify_decision": ("causalrl.identification.decision", "certify_decision"),
    "certify_estimate": ("causalrl.identification.decision", "certify_estimate"),
    "certify_policy": ("causalrl.ope.certify", "certify_policy"),
    "certify_fqe": ("causalrl.scale.d3rlpy", "certify_fqe"),
    "policy_actions": ("causalrl.scale.d3rlpy", "policy_actions"),
    "regimes_from_posterior": ("causalrl.interop.sbi_numpyro", "regimes_from_posterior"),
    "across_regimes": ("causalrl.interop.sbi_numpyro", "across_regimes"),
    "PosteriorRegimeSampler": ("causalrl.interop.sbi_numpyro", "PosteriorRegimeSampler"),
    "ColumnarSimulator": ("causalrl.interop.columnar_sim", "ColumnarSimulator"),
    "simulator_from_callables": ("causalrl.interop.columnar_sim", "simulator_from_callables"),
    "check_conformance": ("causalrl.interop.columnar_sim", "check_conformance"),
    "certify_effect": ("causalrl.estimate.compiler", "certify_effect"),
    "estimate_ate": ("causalrl.estimate.estimators", "estimate_ate"),
    "EffectEstimate": ("causalrl.estimate.estimators", "EffectEstimate"),
    "estimate_sequential_value": ("causalrl.ope.sequential", "estimate_sequential_value"),
    "certify_sequential_value": ("causalrl.ope.sequential", "certify_sequential_value"),
    "SequentialValueEstimate": ("causalrl.ope.sequential", "SequentialValueEstimate"),
    "stream_policy_value": ("causalrl.ope.ipw", "stream_policy_value"),
    "stream_msm_bounds": ("causalrl.bounds.streaming", "stream_msm_bounds"),
    "msm_sensitivity_bounds": ("causalrl.bounds.continuous", "msm_sensitivity_bounds"),
    "certify_sensitivity_bounds": ("causalrl.bounds.continuous", "certify_sensitivity_bounds"),
    "conformal_action_value": ("causalrl.conformal.core", "conformal_action_value"),
    "conformal_quantile": ("causalrl.conformal.core", "conformal_quantile"),
    "split_conformal_interval": ("causalrl.conformal.core", "split_conformal_interval"),
    "cqr_interval": ("causalrl.conformal.core", "cqr_interval"),
    "certify_conformal_interval": ("causalrl.conformal.core", "certify_conformal_interval"),
    "certify_transported_effect": ("causalrl.transport.estimate", "certify_transported_effect"),
    "certify_transported_policy_value": (
        "causalrl.transport.estimate",
        "certify_transported_policy_value",
    ),
    "sequential_ice_values": ("causalrl.ope.sequential", "sequential_ice_values"),
    "AgentType": ("causalrl.magames", "AgentType"),
    "Population": ("causalrl.magames", "Population"),
    "LearnerTopology": ("causalrl.magames", "LearnerTopology"),
    "certify_equilibrium": ("causalrl.magames", "certify_equilibrium"),
    "KindNotLicensedError": ("causalrl.magames", "KindNotLicensedError"),
    "topology_max_kind": ("causalrl.magames", "topology_max_kind"),
    "LinearGaussianPopulationEnv": ("causalrl.magames", "LinearGaussianPopulationEnv"),
    "linear_gaussian_population_env": ("causalrl.magames", "linear_gaussian_population_env"),
    "NoRegretRun": ("causalrl.magames", "NoRegretRun"),
    "run_no_regret": ("causalrl.magames", "run_no_regret"),
    "NoRegretLearner": ("causalrl.agents.no_regret", "NoRegretLearner"),
    "RegretMatching": ("causalrl.agents.no_regret", "RegretMatching"),
    "MultiplicativeWeights": ("causalrl.agents.no_regret", "MultiplicativeWeights"),
    "CCEPolytope": ("causalrl.magames", "CCEPolytope"),
    "cce_polytope": ("causalrl.magames", "cce_polytope"),
    "cce_bounds": ("causalrl.magames", "cce_bounds"),
    "cce_regret": ("causalrl.magames", "cce_regret"),
    "certify_cce_do": ("causalrl.magames", "certify_cce_do"),
    "pettingzoo_to_trajectory_log": ("causalrl.interop.pettingzoo", "pettingzoo_to_trajectory_log"),
    "from_causal_gym": ("causalrl.interop.causal_gym", "from_causal_gym"),
    "MLPMechanism": ("causalrl.scm.continuous.mechanisms", "MLPMechanism"),
    "LocationScaleMechanism": ("causalrl.scm.continuous.mechanisms", "LocationScaleMechanism"),
    "ConditionalFlowMechanism": (
        "causalrl.scm.continuous.mechanisms",
        "ConditionalFlowMechanism",
    ),
    "AmortizedGaussianAbduction": (
        "causalrl.scm.continuous.abduction",
        "AmortizedGaussianAbduction",
    ),
    "abduct_location_scale": ("causalrl.scm.continuous.abduction", "abduct_location_scale"),
    "abduct_invertible": ("causalrl.scm.continuous.abduction", "abduct_invertible"),
    "certify_counterfactual": ("causalrl.scm.continuous.abduction", "certify_counterfactual"),
    "abduct_nuts": ("causalrl.scm.continuous.nuts", "abduct_nuts"),
    "NUTSNoisePosterior": ("causalrl.scm.continuous.nuts", "NUTSNoisePosterior"),
    "certify_nuts_counterfactual": (
        "causalrl.scm.continuous.nuts",
        "certify_nuts_counterfactual",
    ),
    "DecisionCertificate": ("causalrl.identification.decision", "DecisionCertificate"),
    "PolicyValueContrast": ("causalrl.identification.estimate", "PolicyValueContrast"),
    "Certificate": ("causalrl.certify", "Certificate"),
    "Kind": ("causalrl.certify", "Kind"),
    "Assumption": ("causalrl.certify", "Assumption"),
    "EstimandSpec": ("causalrl.certify", "EstimandSpec"),
    "Witness": ("causalrl.certify", "Witness"),
    "Hedge": ("causalrl.certify", "Hedge"),
    "Provenance": ("causalrl.certify", "Provenance"),
    "as_certificate": ("causalrl.certify", "as_certificate"),
    "identify_effect_certified": ("causalrl.certify", "identify_effect_certified"),
    "ipw_sensitivity_bounds_certified": ("causalrl.certify", "ipw_sensitivity_bounds_certified"),
    "msm_policy_value_bounds_certified": ("causalrl.certify", "msm_policy_value_bounds_certified"),
    "manski_bounds": ("causalrl.identification.bounds", "manski_bounds"),
    "conditional_mutual_information": ("causalrl.discovery", "conditional_mutual_information"),
    "counterfactual_expectation": (
        "causalrl.identification.counterfactual",
        "counterfactual_expectation",
    ),
    "cumulative_regret": ("causalrl.eval.metrics", "cumulative_regret"),
    "curriculum_q_learning": ("causalrl.curriculum", "curriculum_q_learning"),
    "discover": ("causalrl.discovery", "discover"),
    "discover_interventional": ("causalrl.discovery", "discover_interventional"),
    "discover_latent": ("causalrl.discovery", "discover_latent"),
    "effect_of_treatment_on_treated": (
        "causalrl.identification.counterfactual",
        "effect_of_treatment_on_treated",
    ),
    "estimate_effect": ("causalrl.identification.id_algorithm", "estimate_effect"),
    "estimate_effect_with_experiments": (
        "causalrl.identification.id_algorithm",
        "estimate_effect_with_experiments",
    ),
    "estimate_transport_general": (
        "causalrl.identification.id_algorithm",
        "estimate_transport_general",
    ),
    "estimate_transported_effect": (
        "causalrl.identification.id_algorithm",
        "estimate_transported_effect",
    ),
    "finite_horizon_regret": ("causalrl.eval.metrics", "finite_horizon_regret"),
    "generate_logs": ("causalrl.data.dataset", "generate_logs"),
    "identify_effect": ("causalrl.identification.id_algorithm", "identify_effect"),
    "identify_effect_with_experiments": (
        "causalrl.identification.id_algorithm",
        "identify_effect_with_experiments",
    ),
    "identify_transport": ("causalrl.identification.id_algorithm", "identify_transport"),
    "identify_transport_general": (
        "causalrl.identification.id_algorithm",
        "identify_transport_general",
    ),
    "imitation_backdoor_set": ("causalrl.imitation", "imitation_backdoor_set"),
    "ipw_value": ("causalrl.ope.ipw", "ipw_value"),
    "is_backdoor_admissible": ("causalrl.identification.transport", "is_backdoor_admissible"),
    "is_gid_identifiable": ("causalrl.identification.id_algorithm", "is_gid_identifiable"),
    "is_identifiable": ("causalrl.identification.criteria", "is_identifiable"),
    "is_identifiable_effect": ("causalrl.identification.id_algorithm", "is_identifiable_effect"),
    "is_imitable": ("causalrl.imitation", "is_imitable"),
    "is_nash_equilibrium": ("causalrl.games", "is_nash_equilibrium"),
    "is_transportable": ("causalrl.identification.transport", "is_transportable"),
    "is_transportable_effect": (
        "causalrl.identification.id_algorithm",
        "is_transportable_effect",
    ),
    "is_transportable_general": (
        "causalrl.identification.id_algorithm",
        "is_transportable_general",
    ),
    "is_valid_curriculum": ("causalrl.curriculum", "is_valid_curriculum"),
    "minimal_intervention_sets": (
        "causalrl.identification.intervention_sets",
        "minimal_intervention_sets",
    ),
    "mixed_nash_equilibria": ("causalrl.games", "mixed_nash_equilibria"),
    "pomis": ("causalrl.identification.intervention_sets", "pomis"),
    "pure_nash_equilibria": ("causalrl.games", "pure_nash_equilibria"),
    "q_learning": ("causalrl.shaping", "q_learning"),
    "report_to_dict": ("causalrl.eval.benchmark", "report_to_dict"),
    "requires_experiment": ("causalrl.identification.intervention_sets", "requires_experiment"),
    "run_episodes": ("causalrl.eval.harness", "run_episodes"),
    "run_confounded_chain_benchmark": ("causalrl.eval.benchmark", "run_confounded_chain_benchmark"),
    "run_frontdoor_benchmark": ("causalrl.eval.benchmark", "run_frontdoor_benchmark"),
    "run_m0_kill_gate": ("causalrl.eval.mbrl_probe", "run_m0_kill_gate"),
    "run_m1_discovery_gate": ("causalrl.eval.mbrl_probe", "run_m1_discovery_gate"),
    "run_m1b_dtr_gate": ("causalrl.eval.mbrl_probe", "run_m1b_dtr_gate"),
    "run_m2_phase_diagram": ("causalrl.eval.mbrl_probe", "run_m2_phase_diagram"),
    "run_m3_function_approx_gate": (
        "causalrl.eval.mbrl_probe",
        "run_m3_function_approx_gate",
    ),
    "transport_estimand": ("causalrl.identification.transport", "transport_estimand"),
    "transport_formula": ("causalrl.identification.transport", "transport_formula"),
    "transported_effect": ("causalrl.identification.transport", "transported_effect"),
    "value_iteration": ("causalrl.shaping", "value_iteration"),
    "ANMFit": ("causalrl.scm.fitters", "ANMFit"),
    "BayesianLinearFit": ("causalrl.scm.continuous.bayesian_fit", "BayesianLinearFit"),
    "CounterfactualBound": (
        "causalrl.identification.counterfactual_bounds",
        "CounterfactualBound",
    ),
    "FitReport": ("causalrl.scm.fit", "FitReport"),
    "LinearGaussianFit": ("causalrl.scm.fitters", "LinearGaussianFit"),
    "NeuralFit": ("causalrl.scm.fitters", "NeuralFit"),
    "NodeFit": ("causalrl.scm.fit", "NodeFit"),
    "PoissonGLMFit": ("causalrl.scm.fitters", "PoissonGLMFit"),
    "TabularCPT": ("causalrl.scm.fitters", "TabularCPT"),
    "counterfactual_interval": (
        "causalrl.identification.counterfactual_bounds",
        "counterfactual_interval",
    ),
    "fit_scm": ("causalrl.scm.fit", "fit_scm"),
    "fit_scm_mec": ("causalrl.scm.fit", "fit_scm_mec"),
    "orient": ("causalrl.discovery", "orient"),
}

#: The public surface, partitioned by what a reader is trying to do.
#:
#: ``__all__`` is a flat list of 250-odd names, which says nothing about where to start. This
#: groups every one of them into exactly one tier -- ``core`` first, then the four subject areas,
#: then the integration surface. It is checked by the test suite to be a true partition of
#: ``__all__``, so a new export cannot be added without being placed, and the API reference is
#: generated in this order.
API_TIERS: dict[str, tuple[str, ...]] = {
    # the names a first-time reader needs; every other tier is reachable from these
    "core": (
        "CausalGraph",
        "CausalMBRLAgent",
        "CausalThompsonSampling",
        "Certificate",
        "NotIdentifiableError",
        "StructuralCausalModel",
        "causal_q_bounds",
        "certify_decision",
        "discover",
        "fit_scm",
        "identify_effect",
        "minimal_intervention_sets",
        "pomis",
        "transported_effect",
    ),
    # graph algorithms, the ID/transport family, and structure learning
    "identification": (
        "AdmissibleInterventions",
        "CPDAG",
        "CounterfactualBound",
        "DecisionCertificate",
        "Domain",
        "Estimand",
        "Interval",
        "MechanismShift",
        "PAG",
        "PivotalityCertificate",
        "PolicyValueContrast",
        "SelectionDiagram",
        "ShiftReport",
        "TransportFormula",
        "TransportRegretCertificate",
        "backdoor_adjustment_set",
        "certify_estimate",
        "certify_transported_effect",
        "certify_transported_policy_value",
        "conditional_mutual_information",
        "confounding_bias_bound",
        "confounding_bias_per_step_bounds",
        "counterfactual_expectation",
        "counterfactual_interval",
        "decision_abstain_mask",
        "decision_flip_rate",
        "discover_interventional",
        "discover_latent",
        "effect_of_treatment_on_treated",
        "estimate_effect",
        "estimate_effect_with_experiments",
        "estimate_transport_general",
        "estimate_transported_effect",
        "identify_effect_with_experiments",
        "identify_transport",
        "identify_transport_general",
        "ipw_sensitivity_bounds",
        "is_backdoor_admissible",
        "is_gid_identifiable",
        "is_identifiable",
        "is_identifiable_effect",
        "is_transportable",
        "is_transportable_effect",
        "is_transportable_general",
        "localize_mechanism_shift",
        "manski_bounds",
        "mi_flip_threshold",
        "msm_contribution_bounds",
        "msm_per_step_bounds",
        "msm_policy_value_bounds",
        "msm_stratified_bounds",
        "orient",
        "pivotality_certificate",
        "requires_experiment",
        "tipping_gamma",
        "transport_estimand",
        "transport_formula",
        "transport_regret_certificate",
    ),
    # structural causal models, their mechanisms, and the data types they consume
    "modelling": (
        "ANMFit",
        "AmortizedGaussianAbduction",
        "BayesianLinearFit",
        "BoundedNodeFit",
        "BoundedSCMFit",
        "CausalEnvProtocol",
        "ConditionalFlowMechanism",
        "ConfoundedTrajectoryDataset",
        "DictNoiseLedger",
        "ExogenousPosterior",
        "FeatureDecisionLog",
        "FidelityReport",
        "FitReport",
        "FunctionalMechanism",
        "LinearGaussianFit",
        "LinearGaussianMechanism",
        "LocationScaleMechanism",
        "LoggedDecision",
        "LoggedDecisions",
        "MLPMechanism",
        "Mechanism",
        "NUTSNoisePosterior",
        "NeuralFit",
        "NeuralMechanism",
        "NodeFit",
        "NoiseLedger",
        "NoisePosterior",
        "PinnedMechanism",
        "PoissonGLMFit",
        "PositivityReport",
        "Regime",
        "SCMCausalEnv",
        "TabularCPT",
        "TrajectoryLog",
        "Transition",
        "abduct_invertible",
        "abduct_location_scale",
        "abduct_nuts",
        "build_unrolled_scm",
        "certify_conformal_interval",
        "certify_counterfactual",
        "certify_fitted_query",
        "certify_nuts_counterfactual",
        "conformal_quantile",
        "cqr_interval",
        "fit_scm_bounded",
        "fit_scm_mec",
        "generate_logs",
        "split_conformal_interval",
    ),
    # agents, environments, interventions, and the multi-agent surface
    "decision": (
        "Agent",
        "AgentType",
        "Anytime",
        "AnytimeInterventionSearch",
        "BackdoorAdjustedAgent",
        "BehavioralCloning",
        "BoundedFittedQIteration",
        "BruteForceInterventionTS",
        "CCEPolytope",
        "CGFAAdvantages",
        "CGFACriticConfig",
        "CGFALosses",
        "CGFAUpdateStats",
        "CausalEnv",
        "CausalEnvWrapper",
        "CausalGame",
        "CausalImitator",
        "CertifiedPolicyAgent",
        "ConfidenceSequence",
        "ConfoundedContextualBandit",
        "ConfoundedGridworld",
        "ConfoundedMDP",
        "Continuous",
        "ContinuousConfoundedBandit",
        "CounterfactualBanditEnv",
        "CounterfactualOptimalPolicy",
        "DOVI",
        "DTREnv",
        "Deadline",
        "DeepDeconfoundedQ",
        "DiscoveryBackdoorAgent",
        "Discrete",
        "FactoredAdvantageConfig",
        "FactoredCritic",
        "FeatureTransition",
        "FittedQIteration",
        "FixedSetThompsonSampling",
        "FunctionApproxBackdoorAgent",
        "GFormulaBackdoorAgent",
        "IdentityEncoder",
        "Intervention",
        "InterventionDomain",
        "InterventionSpace",
        "InterventionalAgent",
        "KindNotLicensedError",
        "LearnerTopology",
        "LinearGaussianPopulationEnv",
        "MABUCEnv",
        "MultiplicativeWeights",
        "NaiveOffline",
        "NaivePOMISThompsonSampling",
        "NaiveThompsonSampling",
        "NoRegretLearner",
        "NoRegretRun",
        "OneHotEncoder",
        "OnlineCausalMBRL",
        "OnlineOnlyUCB",
        "POMISThompsonSampling",
        "Population",
        "PrerequisiteLearner",
        "RBFEncoder",
        "RegretMatching",
        "ScalarAgentAdapter",
        "SearchReport",
        "SequentialDTREnv",
        "SequentialMABUCEnv",
        "SequentialVerdict",
        "SimpsonBandit",
        "StateEncoder",
        "StructuralCausalBanditEnv",
        "TabularMDP",
        "TransportBackdoorAgent",
        "TransportableConfoundedBandit",
        "UCDTR",
        "apply_potential_shaping",
        "best_response",
        "blend_advantages",
        "canonical_intervention",
        "causal_curriculum",
        "causal_potential",
        "cce_bounds",
        "cce_polytope",
        "cce_regret",
        "certify_cce_do",
        "certify_equilibrium",
        "confidence_sequence",
        "conformal_action_value",
        "curriculum_q_learning",
        "encode_batch",
        "factor_gae",
        "factor_rewards",
        "factored_advantage",
        "imitation_backdoor_set",
        "is_imitable",
        "is_nash_equilibrium",
        "is_valid_curriculum",
        "linear_gaussian_population_env",
        "mixed_nash_equilibria",
        "pure_nash_equilibria",
        "q_learning",
        "register_envs",
        "run_no_regret",
        "sequential_policy_comparison",
        "topology_max_kind",
        "value_iteration",
    ),
    # estimators, bounds, and certificates
    "inference": (
        "Assumption",
        "BenchmarkEstimate",
        "EffectEstimate",
        "EstimandSpec",
        "FunctionalManskiBounds",
        "Hedge",
        "Kind",
        "OverlapDiagnostic",
        "Provenance",
        "SequentialValueEstimate",
        "Witness",
        "as_certificate",
        "certify_effect",
        "certify_sensitivity_bounds",
        "certify_sequential_value",
        "cumulative_regret",
        "estimate_ate",
        "estimate_sequential_value",
        "finite_horizon_regret",
        "identify_effect_certified",
        "ipw_sensitivity_bounds_certified",
        "ipw_value",
        "msm_policy_value_bounds_certified",
        "msm_sensitivity_bounds",
        "report_to_dict",
        "run_confounded_chain_benchmark",
        "run_episodes",
        "run_frontdoor_benchmark",
        "run_m0_kill_gate",
        "run_m1_discovery_gate",
        "run_m1b_dtr_gate",
        "run_m2_phase_diagram",
        "run_m3_function_approx_gate",
        "sequential_ice_values",
        "stream_msm_bounds",
        "stream_policy_value",
    ),
    # third-party bridges, scaling adapters, and the exception hierarchy
    "integration": (
        "CausalGraphError",
        "CausalInterfaceUnavailableError",
        "CausalRLError",
        "ColumnarSimulator",
        "PosteriorRegimeSampler",
        "RealizabilityError",
        "UnverifiedAssumptionError",
        "across_regimes",
        "certify_fqe",
        "certify_policy",
        "check_conformance",
        "from_causal_gym",
        "pettingzoo_to_trajectory_log",
        "policy_actions",
        "regimes_from_posterior",
        "simulator_from_callables",
    ),
}

__all__ = [
    "API_TIERS",
    "CPDAG",
    "DOVI",
    "PAG",
    "UCDTR",
    "ANMFit",
    "AdmissibleInterventions",
    "Agent",
    "AgentType",
    "AmortizedGaussianAbduction",
    "Anytime",
    "AnytimeInterventionSearch",
    "Assumption",
    "BackdoorAdjustedAgent",
    "BayesianLinearFit",
    "BehavioralCloning",
    "BenchmarkEstimate",
    "BoundedFittedQIteration",
    "BoundedNodeFit",
    "BoundedSCMFit",
    "BruteForceInterventionTS",
    "CCEPolytope",
    "CGFAAdvantages",
    "CGFACriticConfig",
    "CGFALosses",
    "CGFAUpdateStats",
    "CausalEnv",
    "CausalEnvProtocol",
    "CausalEnvWrapper",
    "CausalGame",
    "CausalGraph",
    "CausalGraphError",
    "CausalImitator",
    "CausalInterfaceUnavailableError",
    "CausalMBRLAgent",
    "CausalRLError",
    "CausalThompsonSampling",
    "Certificate",
    "CertifiedPolicyAgent",
    "ColumnarSimulator",
    "ConditionalFlowMechanism",
    "ConfidenceSequence",
    "ConfoundedContextualBandit",
    "ConfoundedGridworld",
    "ConfoundedMDP",
    "ConfoundedTrajectoryDataset",
    "Continuous",
    "ContinuousConfoundedBandit",
    "CounterfactualBanditEnv",
    "CounterfactualBound",
    "CounterfactualOptimalPolicy",
    "DTREnv",
    "Deadline",
    "DecisionCertificate",
    "DeepDeconfoundedQ",
    "DictNoiseLedger",
    "DiscoveryBackdoorAgent",
    "Discrete",
    "Domain",
    "EffectEstimate",
    "Estimand",
    "EstimandSpec",
    "ExogenousPosterior",
    "FactoredAdvantageConfig",
    "FactoredCritic",
    "FeatureDecisionLog",
    "FeatureTransition",
    "FidelityReport",
    "FitReport",
    "FittedQIteration",
    "FixedSetThompsonSampling",
    "FunctionApproxBackdoorAgent",
    "FunctionalManskiBounds",
    "FunctionalMechanism",
    "GFormulaBackdoorAgent",
    "Hedge",
    "IdentityEncoder",
    "Interval",
    "Intervention",
    "InterventionDomain",
    "InterventionSpace",
    "InterventionalAgent",
    "Kind",
    "KindNotLicensedError",
    "LearnerTopology",
    "LinearGaussianFit",
    "LinearGaussianMechanism",
    "LinearGaussianPopulationEnv",
    "LocationScaleMechanism",
    "LoggedDecision",
    "LoggedDecisions",
    "MABUCEnv",
    "MLPMechanism",
    "Mechanism",
    "MechanismShift",
    "MultiplicativeWeights",
    "NUTSNoisePosterior",
    "NaiveOffline",
    "NaivePOMISThompsonSampling",
    "NaiveThompsonSampling",
    "NeuralFit",
    "NeuralMechanism",
    "NoRegretLearner",
    "NoRegretRun",
    "NodeFit",
    "NoiseLedger",
    "NoisePosterior",
    "NotIdentifiableError",
    "OneHotEncoder",
    "OnlineCausalMBRL",
    "OnlineOnlyUCB",
    "OverlapDiagnostic",
    "POMISThompsonSampling",
    "PinnedMechanism",
    "PivotalityCertificate",
    "PoissonGLMFit",
    "PolicyValueContrast",
    "Population",
    "PositivityReport",
    "PosteriorRegimeSampler",
    "PrerequisiteLearner",
    "Provenance",
    "RBFEncoder",
    "RealizabilityError",
    "Regime",
    "RegretMatching",
    "SCMCausalEnv",
    "ScalarAgentAdapter",
    "SearchReport",
    "SelectionDiagram",
    "SequentialDTREnv",
    "SequentialMABUCEnv",
    "SequentialValueEstimate",
    "SequentialVerdict",
    "ShiftReport",
    "SimpsonBandit",
    "StateEncoder",
    "StructuralCausalBanditEnv",
    "StructuralCausalModel",
    "TabularCPT",
    "TabularMDP",
    "TrajectoryLog",
    "Transition",
    "TransportBackdoorAgent",
    "TransportFormula",
    "TransportRegretCertificate",
    "TransportableConfoundedBandit",
    "UnverifiedAssumptionError",
    "Witness",
    "__version__",
    "abduct_invertible",
    "abduct_location_scale",
    "abduct_nuts",
    "across_regimes",
    "apply_potential_shaping",
    "as_certificate",
    "backdoor_adjustment_set",
    "best_response",
    "blend_advantages",
    "build_unrolled_scm",
    "canonical_intervention",
    "causal_curriculum",
    "causal_potential",
    "causal_q_bounds",
    "cce_bounds",
    "cce_polytope",
    "cce_regret",
    "certify_cce_do",
    "certify_conformal_interval",
    "certify_counterfactual",
    "certify_decision",
    "certify_effect",
    "certify_equilibrium",
    "certify_estimate",
    "certify_fitted_query",
    "certify_fqe",
    "certify_nuts_counterfactual",
    "certify_policy",
    "certify_sensitivity_bounds",
    "certify_sequential_value",
    "certify_transported_effect",
    "certify_transported_policy_value",
    "check_conformance",
    "conditional_mutual_information",
    "confidence_sequence",
    "conformal_action_value",
    "conformal_quantile",
    "confounding_bias_bound",
    "confounding_bias_per_step_bounds",
    "counterfactual_expectation",
    "counterfactual_interval",
    "cqr_interval",
    "cumulative_regret",
    "curriculum_q_learning",
    "decision_abstain_mask",
    "decision_flip_rate",
    "discover",
    "discover_interventional",
    "discover_latent",
    "effect_of_treatment_on_treated",
    "encode_batch",
    "estimate_ate",
    "estimate_effect",
    "estimate_effect_with_experiments",
    "estimate_sequential_value",
    "estimate_transport_general",
    "estimate_transported_effect",
    "factor_gae",
    "factor_rewards",
    "factored_advantage",
    "finite_horizon_regret",
    "fit_scm",
    "fit_scm_bounded",
    "fit_scm_mec",
    "from_causal_gym",
    "generate_logs",
    "identify_effect",
    "identify_effect_certified",
    "identify_effect_with_experiments",
    "identify_transport",
    "identify_transport_general",
    "imitation_backdoor_set",
    "ipw_sensitivity_bounds",
    "ipw_sensitivity_bounds_certified",
    "ipw_value",
    "is_backdoor_admissible",
    "is_gid_identifiable",
    "is_identifiable",
    "is_identifiable_effect",
    "is_imitable",
    "is_nash_equilibrium",
    "is_transportable",
    "is_transportable_effect",
    "is_transportable_general",
    "is_valid_curriculum",
    "linear_gaussian_population_env",
    "localize_mechanism_shift",
    "manski_bounds",
    "mi_flip_threshold",
    "minimal_intervention_sets",
    "mixed_nash_equilibria",
    "msm_contribution_bounds",
    "msm_per_step_bounds",
    "msm_policy_value_bounds",
    "msm_policy_value_bounds_certified",
    "msm_sensitivity_bounds",
    "msm_stratified_bounds",
    "orient",
    "pettingzoo_to_trajectory_log",
    "pivotality_certificate",
    "policy_actions",
    "pomis",
    "pure_nash_equilibria",
    "q_learning",
    "regimes_from_posterior",
    "register_envs",
    "report_to_dict",
    "requires_experiment",
    "run_confounded_chain_benchmark",
    "run_episodes",
    "run_frontdoor_benchmark",
    "run_m0_kill_gate",
    "run_m1_discovery_gate",
    "run_m1b_dtr_gate",
    "run_m2_phase_diagram",
    "run_m3_function_approx_gate",
    "run_no_regret",
    "sequential_ice_values",
    "sequential_policy_comparison",
    "simulator_from_callables",
    "split_conformal_interval",
    "stream_msm_bounds",
    "stream_policy_value",
    "tipping_gamma",
    "topology_max_kind",
    "transport_estimand",
    "transport_formula",
    "transport_regret_certificate",
    "transported_effect",
    "value_iteration",
]


def __getattr__(name: str) -> object:
    target = _EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute = target
    try:
        value = _cast(object, getattr(_import_module(module_name), attribute))
    except ModuleNotFoundError as exc:
        if exc.name == "torch":
            raise ImportError(
                f"{name} requires PyTorch support; install the 'causalrl[torch]' extra"
            ) from exc
        raise
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
